[package]
name = "little_turing_machine"
version = "0.0.1"
authors = ["Joël"]
edition = "2021"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
nannou = "0.18.1"
once_cell = "1.18.0"
test-case = "3.1.0"
